### ISSUE TITLE
[FR] Add support for AD

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/gnome-online-accounts-gtk#10]
- Login: Implement a secure login system allowing users to authenticate their identities.
- Resource Sharing: Enable the sharing of resources such as files and printers among authenticated users.
- File Management: Implement file management functionalities to allow users to create, access, modify, and delete files securely.

https://github.com/ubuntu/adsys

![image](https://github.com/linuxmint/gnome-online-accounts-gtk/assets/23406555/e284b038-b465-4da6-b3e6-9de1955c9143)

**Comment by leigh123linux** [comment]
File the issue against gnome-online-accounts upstream.

https://gitlab.gnome.org/GNOME/gnome-online-accounts
