### ISSUE TITLE
Translation doubt

### ISSUE THREAD

**Issue by hugok79** [linuxmint/gnome-online-accounts-gtk#3]
What does **<b>%s</b>** refers to? 

https://github.com/linuxmint/gnome-online-accounts-gtk/blob/febc445ef3e947d1ede4cb631df4718bcd6e0463/gnome-online-accounts-gtk.pot#L27

**Comment by mtwebster** [comment]
That would be something like "joe@gmail.com removed" - the second line of the account below the provider name.

**Comment by mtwebster** [comment]
Weird there's actually a comment there that should be in the potfile describing this, I'll try to fix.

**Comment by hugok79** [comment]
@mtwebster Ok thanks. The doubt was because in Portuguese language we have the feminine(ends with `a`) and masculineends with `o`) grammatical genders.
